services: 

  db: 

    image: magegr/sqlpinacoteca:v1 

    container_name: contenedorPinacoteca 

    ports: 

      - "3306:3306" 

    networks: 

      - mi-red 

 

  app: 

    image: magegr/phppinacoteca:v1 

    container_name: contenedorMiApp 

    ports: 

      - "8080:80" 

    depends_on: 

      - db 

    networks: 

      - mi-red 

 

  phpmyadmin: 

    image: phpmyadmin/phpmyadmin:latest 

    container_name: contenedorPhpMyAdmin 

    environment: 

      PMA_HOST: db 

      MYSQL_ROOT_PASSWORD: contrasenyaRoot 

    ports: 

      - "8081:80" 

    depends_on: 

      - db 

    networks: 

      - mi-red 

 

networks: 

  mi-red: 

    driver: bridge 